// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: pkg/relay/transport/proto/heartbeat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HeartbeatRequest contains heartbeat information
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *ClientMetrics         `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	TransportMode string                 `protobuf:"bytes,5,opt,name=transport_mode,json=transportMode,proto3" json:"transport_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_relay_transport_proto_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HeartbeatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetMetrics() *ClientMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HeartbeatRequest) GetTransportMode() string {
	if x != nil {
		return x.TransportMode
	}
	return ""
}

// HeartbeatResponse contains heartbeat acknowledgment
type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	ServerMetrics   *ServerMetrics         `protobuf:"bytes,4,opt,name=server_metrics,json=serverMetrics,proto3" json:"server_metrics,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_relay_transport_proto_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatResponse) GetServerTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTimestamp
	}
	return nil
}

func (x *HeartbeatResponse) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HeartbeatResponse) GetServerMetrics() *ServerMetrics {
	if x != nil {
		return x.ServerMetrics
	}
	return nil
}

func (x *HeartbeatResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// HealthRequest requests health status
type HealthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	IncludeMetrics bool                   `protobuf:"varint,2,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_relay_transport_proto_heartbeat_proto_rawDescGZIP(), []int{2}
}

func (x *HealthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HealthRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

// HealthResponse contains health status
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	UptimeSeconds int32                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ClientMetrics *ClientMetrics         `protobuf:"bytes,5,opt,name=client_metrics,json=clientMetrics,proto3" json:"client_metrics,omitempty"`
	ServerMetrics *ServerMetrics         `protobuf:"bytes,6,opt,name=server_metrics,json=serverMetrics,proto3" json:"server_metrics,omitempty"`
	Warnings      []string               `protobuf:"bytes,7,rep,name=warnings,proto3" json:"warnings,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_relay_transport_proto_heartbeat_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *HealthResponse) GetUptimeSeconds() int32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetClientMetrics() *ClientMetrics {
	if x != nil {
		return x.ClientMetrics
	}
	return nil
}

func (x *HealthResponse) GetServerMetrics() *ServerMetrics {
	if x != nil {
		return x.ServerMetrics
	}
	return nil
}

func (x *HealthResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *HealthResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ClientMetrics contains client-side metrics
type ClientMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BytesSent         int64                  `protobuf:"varint,1,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived     int64                  `protobuf:"varint,2,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	PacketsSent       int64                  `protobuf:"varint,3,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsReceived   int64                  `protobuf:"varint,4,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	ActiveTunnels     int32                  `protobuf:"varint,5,opt,name=active_tunnels,json=activeTunnels,proto3" json:"active_tunnels,omitempty"`
	ActiveP2PSessions int32                  `protobuf:"varint,6,opt,name=active_p2p_sessions,json=activeP2pSessions,proto3" json:"active_p2p_sessions,omitempty"`
	CpuUsage          float64                `protobuf:"fixed64,7,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage       float64                `protobuf:"fixed64,8,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	TransportMode     string                 `protobuf:"bytes,9,opt,name=transport_mode,json=transportMode,proto3" json:"transport_mode,omitempty"`
	LastSwitch        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_switch,json=lastSwitch,proto3" json:"last_switch,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientMetrics) Reset() {
	*x = ClientMetrics{}
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMetrics) ProtoMessage() {}

func (x *ClientMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMetrics.ProtoReflect.Descriptor instead.
func (*ClientMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_relay_transport_proto_heartbeat_proto_rawDescGZIP(), []int{4}
}

func (x *ClientMetrics) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *ClientMetrics) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *ClientMetrics) GetPacketsSent() int64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *ClientMetrics) GetPacketsReceived() int64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *ClientMetrics) GetActiveTunnels() int32 {
	if x != nil {
		return x.ActiveTunnels
	}
	return 0
}

func (x *ClientMetrics) GetActiveP2PSessions() int32 {
	if x != nil {
		return x.ActiveP2PSessions
	}
	return 0
}

func (x *ClientMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ClientMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ClientMetrics) GetTransportMode() string {
	if x != nil {
		return x.TransportMode
	}
	return ""
}

func (x *ClientMetrics) GetLastSwitch() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSwitch
	}
	return nil
}

// ServerMetrics contains server-side metrics
type ServerMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectedClients int32                  `protobuf:"varint,1,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	ActiveTunnels    int32                  `protobuf:"varint,2,opt,name=active_tunnels,json=activeTunnels,proto3" json:"active_tunnels,omitempty"`
	ServerLoad       float64                `protobuf:"fixed64,3,opt,name=server_load,json=serverLoad,proto3" json:"server_load,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerMetrics) Reset() {
	*x = ServerMetrics{}
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetrics) ProtoMessage() {}

func (x *ServerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_relay_transport_proto_heartbeat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetrics.ProtoReflect.Descriptor instead.
func (*ServerMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_relay_transport_proto_heartbeat_proto_rawDescGZIP(), []int{5}
}

func (x *ServerMetrics) GetConnectedClients() int32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

func (x *ServerMetrics) GetActiveTunnels() int32 {
	if x != nil {
		return x.ActiveTunnels
	}
	return 0
}

func (x *ServerMetrics) GetServerLoad() float64 {
	if x != nil {
		return x.ServerLoad
	}
	return 0
}

func (x *ServerMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_pkg_relay_transport_proto_heartbeat_proto protoreflect.FileDescriptor

const file_pkg_relay_transport_proto_heartbeat_proto_rawDesc = "" +
	"\n" +
	")pkg/relay/transport/proto/heartbeat.proto\x12\brelay.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x121\n" +
	"\ametrics\x18\x04 \x01(\v2\x17.relay.v1.ClientMetricsR\ametrics\x12%\n" +
	"\x0etransport_mode\x18\x05 \x01(\tR\rtransportMode\"\x82\x02\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12E\n" +
	"\x10server_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fserverTimestamp\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x05R\x0fintervalSeconds\x12>\n" +
	"\x0eserver_metrics\x18\x04 \x01(\v2\x17.relay.v1.ServerMetricsR\rserverMetrics\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"U\n" +
	"\rHealthRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0finclude_metrics\x18\x02 \x01(\bR\x0eincludeMetrics\"\xed\x02\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12A\n" +
	"\x0elast_heartbeat\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x05R\ruptimeSeconds\x12>\n" +
	"\x0eclient_metrics\x18\x05 \x01(\v2\x17.relay.v1.ClientMetricsR\rclientMetrics\x12>\n" +
	"\x0eserver_metrics\x18\x06 \x01(\v2\x17.relay.v1.ServerMetricsR\rserverMetrics\x12\x1a\n" +
	"\bwarnings\x18\a \x03(\tR\bwarnings\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\x9e\x03\n" +
	"\rClientMetrics\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x01 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x02 \x01(\x03R\rbytesReceived\x12!\n" +
	"\fpackets_sent\x18\x03 \x01(\x03R\vpacketsSent\x12)\n" +
	"\x10packets_received\x18\x04 \x01(\x03R\x0fpacketsReceived\x12%\n" +
	"\x0eactive_tunnels\x18\x05 \x01(\x05R\ractiveTunnels\x12.\n" +
	"\x13active_p2p_sessions\x18\x06 \x01(\x05R\x11activeP2pSessions\x12\x1b\n" +
	"\tcpu_usage\x18\a \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\b \x01(\x01R\vmemoryUsage\x12%\n" +
	"\x0etransport_mode\x18\t \x01(\tR\rtransportMode\x12;\n" +
	"\vlast_switch\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSwitch\"\xbe\x01\n" +
	"\rServerMetrics\x12+\n" +
	"\x11connected_clients\x18\x01 \x01(\x05R\x10connectedClients\x12%\n" +
	"\x0eactive_tunnels\x18\x02 \x01(\x05R\ractiveTunnels\x12\x1f\n" +
	"\vserver_load\x18\x03 \x01(\x01R\n" +
	"serverLoad\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xec\x01\n" +
	"\x10HeartbeatService\x12H\n" +
	"\rSendHeartbeat\x12\x1a.relay.v1.HeartbeatRequest\x1a\x1b.relay.v1.HeartbeatResponse\x12N\n" +
	"\x0fStreamHeartbeat\x12\x1a.relay.v1.HeartbeatRequest\x1a\x1b.relay.v1.HeartbeatResponse(\x010\x01\x12>\n" +
	"\tGetHealth\x12\x17.relay.v1.HealthRequest\x1a\x18.relay.v1.HealthResponseBGZEgithub.com/2gc-dev/cloudbridge-client/pkg/relay/transport/proto;protob\x06proto3"

var (
	file_pkg_relay_transport_proto_heartbeat_proto_rawDescOnce sync.Once
	file_pkg_relay_transport_proto_heartbeat_proto_rawDescData []byte
)

func file_pkg_relay_transport_proto_heartbeat_proto_rawDescGZIP() []byte {
	file_pkg_relay_transport_proto_heartbeat_proto_rawDescOnce.Do(func() {
		file_pkg_relay_transport_proto_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_relay_transport_proto_heartbeat_proto_rawDesc), len(file_pkg_relay_transport_proto_heartbeat_proto_rawDesc)))
	})
	return file_pkg_relay_transport_proto_heartbeat_proto_rawDescData
}

var file_pkg_relay_transport_proto_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_relay_transport_proto_heartbeat_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),      // 0: relay.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 1: relay.v1.HeartbeatResponse
	(*HealthRequest)(nil),         // 2: relay.v1.HealthRequest
	(*HealthResponse)(nil),        // 3: relay.v1.HealthResponse
	(*ClientMetrics)(nil),         // 4: relay.v1.ClientMetrics
	(*ServerMetrics)(nil),         // 5: relay.v1.ServerMetrics
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_pkg_relay_transport_proto_heartbeat_proto_depIdxs = []int32{
	6,  // 0: relay.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 1: relay.v1.HeartbeatRequest.metrics:type_name -> relay.v1.ClientMetrics
	6,  // 2: relay.v1.HeartbeatResponse.server_timestamp:type_name -> google.protobuf.Timestamp
	5,  // 3: relay.v1.HeartbeatResponse.server_metrics:type_name -> relay.v1.ServerMetrics
	6,  // 4: relay.v1.HealthResponse.last_heartbeat:type_name -> google.protobuf.Timestamp
	4,  // 5: relay.v1.HealthResponse.client_metrics:type_name -> relay.v1.ClientMetrics
	5,  // 6: relay.v1.HealthResponse.server_metrics:type_name -> relay.v1.ServerMetrics
	6,  // 7: relay.v1.ClientMetrics.last_switch:type_name -> google.protobuf.Timestamp
	6,  // 8: relay.v1.ServerMetrics.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 9: relay.v1.HeartbeatService.SendHeartbeat:input_type -> relay.v1.HeartbeatRequest
	0,  // 10: relay.v1.HeartbeatService.StreamHeartbeat:input_type -> relay.v1.HeartbeatRequest
	2,  // 11: relay.v1.HeartbeatService.GetHealth:input_type -> relay.v1.HealthRequest
	1,  // 12: relay.v1.HeartbeatService.SendHeartbeat:output_type -> relay.v1.HeartbeatResponse
	1,  // 13: relay.v1.HeartbeatService.StreamHeartbeat:output_type -> relay.v1.HeartbeatResponse
	3,  // 14: relay.v1.HeartbeatService.GetHealth:output_type -> relay.v1.HealthResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_relay_transport_proto_heartbeat_proto_init() }
func file_pkg_relay_transport_proto_heartbeat_proto_init() {
	if File_pkg_relay_transport_proto_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_relay_transport_proto_heartbeat_proto_rawDesc), len(file_pkg_relay_transport_proto_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_relay_transport_proto_heartbeat_proto_goTypes,
		DependencyIndexes: file_pkg_relay_transport_proto_heartbeat_proto_depIdxs,
		MessageInfos:      file_pkg_relay_transport_proto_heartbeat_proto_msgTypes,
	}.Build()
	File_pkg_relay_transport_proto_heartbeat_proto = out.File
	file_pkg_relay_transport_proto_heartbeat_proto_goTypes = nil
	file_pkg_relay_transport_proto_heartbeat_proto_depIdxs = nil
}
